### PR TITLE
Extensibility Refactor

### PR DESCRIPTION
**Pull request by yawpitch**
This is a _considerable_ refactor meant to allow easier extension and addition of new analyzers for other exercises.

The most significant changes:

1. Adds a lib/common area and extends the bin/analyze.py, lib/two-fer, and tests to utilize this common functionality. Should make writing of analyzers much simpler as a lot of boilerplate is refactored away.
2. Updates path handling and imports, and refactors significant constants into Enum subclasses for easy identification.
3. Adds a mixin to make the creation of test suites for analyzers easier
4. Moves exericse unit tests into their own subdirectory.
5. Tests will now write to a /tmp folder that will be cleaned up at test completion.
6. Return value of the **analyze** function is now an Analyze instance (subclass of **dict**) with some nicer attribute access.

Thoughts for more improvements mainly involve adding some basic logging.

Calling it a WIP because I want to hear what everyone thinks about this large of a PR first.

### CODE REVIEW

**Comment by iHiD** [comment]
I have nothing to add as I don't really speak Python, but thank you for doing this @yawpitch! :)

**Comment by yawpitch** [comment]
Updated this PR to reflect changes made in exercism/automated-mentoring-support#56.

@exercism/python-analyzer, would love to have some input on this from those who do speak Python.

**Comment by TreyAguirre** [comment]
Just read through all these changes and they look great @yawpitch ! Much more extensible and elegant than the previous version. I'm ready to merge this unless you want more feedback or want to make additional changes. Just @ me here or on Slack when you feel it's ready.

**Comment by yawpitch** [comment]
@TreyAguirre happy to merge, if you don't think it'll cause too much disruption to others. I've tried to make it pretty obvious and an analyzer should be pretty much a matter of "define your **Comments** and your **analyze**, build your tests, and `pytest -x`", but it's quite a substantial refactor and introduces a lot of usage of **pathlib** and **enum** that might be unfamiliar to some.

I was considering taking a whack at a few exercises ... `hamming`, `isogram`, `raindrops` ... there are several Core exercises that seem to stay on the backlog for quite some time but have fairly well understood optimal solutions. Happy to collaborate as well.

**Comment by SleeplessByte** [comment]
Funny, a lot of these changes actually match what we've done at JS/TS. I'd say they are great!

Did Python go through the Project Track Anatomy? (cc @F3PiX). If so, I think it's best to work the order of the track. But mostly, look for exercises with a _clear / single / easy_ solution. `hamming`, `isogram` and `raindrops` are probably _quite a bit of work_ to analyse!.

`two-fer`, `gigasecond`, and the `resistor-color`, if part of the track are probably easier candidates to tackle first!

**Comment by yawpitch** [comment]
@SleeplessByte as far as I know Python is only part way through Track Anatomy, I believe it's completed a very rough Round 1, though honestly it's a bit of a nebulous, ill-defined process and considering the popularity of Python and the _obvious_ backlog it'd be good if we could define it a little better.

**Comment by SleeplessByte** [comment]
PTA is not yet a perfectly defined project; if you had a first round, the track _should_ be in an okay shape for now. I'll ask if they can speed up round 2 for ya.

**Comment by yawpitch** [comment]
Looks like I may be getting involved with Round 2, so  hopefully we can get some traction on this soon, as we really need to focus the effort on analyzers towards the thin end of the wedge.

**Pull request merged**
